import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  floatingLabel: {
    fontSize: 13,
    color: '#A1A2A1',
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    height: 18,
    textAlignVertical: 'center',
    lineHeight: 18,
    zIndex: 10,
  },
  floatingLabelActive: {
  color: '#A2D033',
    fontSize: 13,
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    height: 18,
    textAlignVertical: 'center',
    lineHeight: 18,
    zIndex: 10,
  },
  floatingLabelError: {
  color: '#E53935',
    fontSize: 13,
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    height: 18,
    textAlignVertical: 'center',
    lineHeight: 18,
    zIndex: 10,
  },
  floatingLabelCutWrapper: {
    position: 'absolute',
    top: -14,
    left: 38,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    height: 18,
  },
  floatingLabelCutBg: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#F7F7F7',
    zIndex: 9,
    borderRadius: 8,
    height: 18,
    width: '100%',
  },
  dateText: {
    fontSize: 16,
    color: '#424242',
    paddingVertical: 6,
  },
  textError: {
    color: '#E53935',
    fontSize: 12,
    marginTop: 2,
    marginLeft: 8,
    marginBottom: 8,
  },
});
