import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  floatingLabelCutWrapper: {
    position: 'absolute',
    top: -14,
    left: 38,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    height: 18,
  },
  floatingLabelCutBg: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#F7F7F7',
    zIndex: 9,
    borderRadius: 8,
    height: 18,
    width: '100%',
  },
  floatingLabel: {
    fontSize: 13,
    color: '#A1A2A1',
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    height: 18,
    textAlignVertical: 'center',
    lineHeight: 18,
    zIndex: 10,
  },
  selectText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: '#424242',
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 50,
    lineHeight: 50,
    paddingTop: 0,
    paddingBottom: 0,
    textAlignVertical: 'center',
    includeFontPadding: false,
    textAlign: 'left',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    minWidth: 240,
    maxWidth: 320,
    elevation: 4,
  },
  optionItem: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  optionText: {
    fontSize: 16,
    color: '#222',
    ...(Platform.OS === 'ios' ? { textAlign: 'center' } : {}),
  },
  closeBtn: {
    marginTop: 12,
    alignSelf: 'flex-end',
    padding: 8,
  },
  closeBtnText: {
    color: '#A1A2A1',
    fontWeight: 'bold',
    fontSize: 15,
  },
  searchInput: {
    padding: 10,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    marginBottom: 10,
    fontSize: 15,
    color: '#222',
    backgroundColor: '#F7F7F7',
    borderRadius: 6,
  },
  list: {
    flexGrow: 1,
    maxHeight: 300,
  },
  textError: {
    color: '#E53935',
    fontSize: 13,
    marginTop: 4,
    marginLeft: 16,
  },
});
